import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import LeftSideBar from "@/components/layout/LeftSideBar";
import TopBar from "@/components/layout/TobBer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
        <div className="flex max-lg:flex-col text-slate-800">
            <LeftSideBar />
            <TopBar></TopBar>
      
            <div className="flex-1">{children}</div>
          </div>
          
          
          {children}</body>
      </html>
    </ClerkProvider>
  );
}
